theme: jekyll-theme-cayman
#google_analytics: G-REDJ02G086
# Analytics
analytics:
  provider               : "google-gtag"
  google:
    measurement_id          : "G-REDJ02G086"
    anonymize_ip         : # true, false (default)
